Задание 0.
Перепишите следующий код, используя ресурсный try

public void rwLine(Path pathRead, Path pathWrite) throws IOException {
    BufferedReader in = null;
    BufferedWriter out = null;
    try {
        in = Files.newBufferedReader(pathRead);
        out = Files.newBufferedWriter(pathWrite);
        out.write(in.readLine());
    } finally {
        try {
            if (in != null) in.close();
        } catch (IOException e) {



        }
        try {
        if (out != null) out.close();
        } catch (IOException e) {



        }
    }
}



Задание 1.
Создайте метод doSomething(), который может быть источником одного из типов checked exceptions (тело самого метода
прописывать не обязательно). Вызовите этот метод из main и обработайте в нем исключение, которое вызвал метод
doSomething().


Задание 2.
Создайте класс Счетчик, у которого есть метод add(), увеличивающий значение внутренней int переменной на 1. Сделайте
так, чтобы с объектом такого типа можно было работать в блоке try-with-resources. Подумайте, что должно происходить при
закрытии этого ресурса? Напишите метод для проверки, закрыт ли ресурс. При попытке вызвать add() у закрытого ресурса,
должен выброситься IOException


Задание 3.
1. Создайте класс исключения, который будет выбрасываться при делении на 0. Исключение должно отображать понятное для
пользователя сообщение об ошибке;
2. Создайте класс исключений, которое будет возникать при обращении к пустому элементу в массиве ссылочного типа.
Исключение должно отображать понятное для пользователя сообщение об ошибке;
3. Создайте класс исключения, которое будет возникать при попытке открыть несуществующий файл. Исключение должно
отображать понятное для пользователя сообщение об ошибке.


Задание 4.
1. Напишите метод, на вход которого подаётся двумерный строковый массив размером 4х4. При подаче массива другого размера
необходимо бросить исключение MyArraySizeException.
2. Далее метод должен пройтись по всем элементам массива, преобразовать в int и просуммировать. Если в каком-то элементе
массива преобразование не удалось (например, в ячейке лежит символ или текст вместо числа), должно быть брошено
исключение MyArrayDataException с детализацией, в какой именно ячейке лежат неверные данные.
3. В методе main() вызвать полученный метод, обработать возможные исключения MyArraySizeException и MyArrayDataException
и вывести результат расчета (сумму элементов, при условии, что подали на вход корректный массив).



